### ISSUE TITLE
Allow undo of file deletions

### ISSUE THREAD

**Issue by second-story** [tchx84/Portfolio#106]
As of Portfolio 0.9.8, deleting a file offers no undo option.  Deleting files through Portfolio seems more akin to running the `rm` command via the terminal, and the complete removal of the file can be challenging and disruptive for users who are more accustomed to GUI apps.  

After deleting a file (or files), it would be helpful to add a overlay for a few seconds asking to undo the delete.  The Nautilus file manager handles this behavior very well, for comparison.

**Comment by tchx84** [comment]
hey @second-story , thanks for reaching out!

> As of Portfolio 0.9.8, deleting a file offers no undo option. Deleting files through Portfolio seems more akin to running the `rm` command via the terminal, and the complete removal of the file can be challenging and disruptive for users who are more accustomed to GUI apps.
> 

There are plans for this (someone already volunteered to implement it) but, it will take a while until it lands. It will require some extra-clever design work.

> After deleting a file (or files), it would be helpful to add a overlay for a few seconds asking to undo the delete. The Nautilus file manager handles this behavior very well, for comparison.

Other file managers offer a "Move to Trash" option, which is very explicit. Just like these are very explicit when someone use `shift+del`.

As for Portfolio, as a short term improvement, could include the word "permanently" to the confirmation message, so is even more explicit.

**Comment by second-story** [comment]
I think that's a great idea, @tchx84, and I appreciate that extra cue being included until the larger implementation is in place.  Having extra info that highlights the permanence of the current delete action will really help give users proper expectations.

**Comment by tchx84** [comment]
@aVolpe let me know when you're getting started with this, so we can discuss the design.
