### ISSUE TITLE
Designer review

### ISSUE THREAD

**Issue by tchx84** [tchx84/Portfolio#13]
Hey @bertob , I am sure you are busy but, if you happen to have the time to try this app I made for my phone, I would appreciate your feedback.

TLDR; I didn't like the UX of existing file managers available for phones, so I started this a weekend project. Here's a very short [summary](https://github.com/tchx84/Portfolio/blob/master/CHANGELOG.md) of all it can do:

**Comment by bertob** [comment]
Some quick thoughts after building it:
- the huge symbolics don't look great, I'd either use fullcolor icons like Nautilus does, or use the symoblics at their nominal size, perhaps wrapped in a circle to make them work in the layout?
- the content area has a double border
- the primary menu looks weird and unfinished
- primary menu entries should be left-aligned
- search seems to only work in the current folder, which is confusing
- the pathbar looks weird isn't very helpful at narrow widths anyway, so I wonder if it'd make more sense to just have a centered title with the name of the current folder instead

![image](https://user-images.githubusercontent.com/1908896/102624885-f04b9980-4144-11eb-8316-178b78b5ed39.png)

**Comment by tchx84** [comment]
> Some quick thoughts after building it:

Awesome, any thoughts about the interaction model?

**Comment by tchx84** [comment]
Sorry, I had a long day at work, here my questions:

> * the huge symbolics don't look great, I'd either use fullcolor icons like Nautilus does, or use the symoblics at their nominal size, perhaps wrapped in a circle to make them work in the layout?

You mean something like this?

![image](https://user-images.githubusercontent.com/481418/102675949-20f9f600-417a-11eb-8978-05b5464239e9.png)

> * the content area has a double border

Nice catch.

> * the primary menu looks weird and unfinished

Because it is :laughing: 

> * primary menu entries should be left-aligned

Got it.

> * search seems to only work in the current folder, which is confusing

Yes, it is actually filter, not really search... but I couldn't find a proper icon.

> * the pathbar looks weird isn't very helpful at narrow widths anyway, so I wonder if it'd make more sense to just have a centered title with the name of the current folder instead

Well, we can try it :smile: 

@bertob last thing, I am really interested in your feedback regarding the interaction model (e.g. for multi-selection) and my design for the bottom action behavior.

Thanks!!

**Comment by bertob** [comment]
Tried the latest commit again, a few more notes:
- The window title is not centered on the window
- Long press to select is undiscoverable on non-touch, so I would never have found it without you pointing it out. Maybe right click to select could work here?
- There's no spacing between the delete and edit buttons
- I don't think the empty box works for exiting selection mode. I'd try either a "Cancel" button, or maybe an x button on the right side

Anything else you specifically want feedback on?

**Comment by tchx84** [comment]
> Tried the latest commit again, a few more notes:
> 
> * The window title is not centered on the window

Good catch!

> * Long press to select is undiscoverable on non-touch, so I would never have found it without you pointing it out. Maybe right click to select could work here?

Well, I am not really aiming non-mobile here but I could add it :)

> * There's no spacing between the delete and edit buttons

Got it.

> * I don't think the empty box works for exiting selection mode. I'd try either a "Cancel" button, or maybe an x button on the right side
> 

Well, I could use the close button I use for the embedded about screen (check it out!)

> Anything else you specifically want feedback on?

Not really, this is all great feedback, thanks!

**Comment by bertob** [comment]
> Well, I could use the close button I use for the embedded about screen (check it out!)

Hmm that's a bit weird, I'm not a fan. I'd do a normal HdyDeck here, and have a headerbar with a back button, "About" as the title, and nothing on the right. That way you also get a nice swipe back gesture for free :)

![image](https://user-images.githubusercontent.com/1908896/102695532-42192000-4228-11eb-9d27-654de737788d.png)

What I was thinking of for the selection mode action bar was just a `.flat` button with an x.

One more thing: Would be good to use HdyWindow to get rounded bottom corners when it's not tiled/maximized.

**Comment by tchx84** [comment]
haha, now I am falling behind the feedback...

I am still struggling with that titled being not centered, the issue is that the label is inside a container, and he container is the custom tittle. So the label is centering for the container, not for the header bar.

> Hmm that's a bit weird, I'm not a fan. I'd do a normal HdyDeck here, and have a headerbar with a back button, "About" as the title, and nothing on the right. That way you also get a nice swipe back gesture for free :)

Ill check HdyDeck.

> What I was thinking of for the selection mode action bar was just a `.flat` button with an x.
> 

Ill try it out.

> One more thing: Would be good to use HdyWindow to get rounded bottom corners when it's not tiled/maximized.

Alright!

**Comment by bertob** [comment]
> I am still struggling with that titled being not centered, the issue is that the label is inside a container, and he container is the custom tittle. So the label is centering for the container, not for the header bar.

I recommend joining the the podcasts or libhandy channels on Matrix, the people there can definitely help with this :)

**Comment by tchx84** [comment]
@bertob I implemented most of your suggestion, and created issues for the remaining ones, thanks, as usual, for your feedback with this weekend project.
