### ISSUE TITLE
Allow to unmount external volumes

### ISSUE THREAD

**Issue by tchx84** [tchx84/Portfolio#14]

**Comment by tchx84** [comment]
No complains about this so far, so let's close it for now.

**Comment by GNUuser** [comment]
Hola. Es posible reabrir  esta función. Usuarios de Posh nesecitan un botón de desmonte para SDs. 
https://forums.puri.sm/t/discovering-l5/12399/4

**Comment by tchx84** [comment]
> Hola. Es posible reabrir esta función?. Usuarios de Posh nesecitan un botón para desmontar tarjetas SD y USB drives.
> https://forums.puri.sm/t/discovering-l5/12399/4

Si, pero no creo que llegue para el release del Lunes. Estoy teniendo un problema al desmontar y lo tengo que investigar, le das una prueba?

**Comment by GNUuser** [comment]
Tranquilo, toma todo el tiempo posible hasta que quede bien el desmonte, lo mas importante es que pronto tendremos esa función  en Portfolio.

**Comment by tchx84** [comment]
> Tranquilo, toma todo el tiempo posible hasta que quede bien el desmonte, lo mas importante es que pronto tendremos esa función en Portfolio.

Lo tengo listo, lo que te estoy pidiendo es que ayudes con el testing :) si puedes probar me ayudará.
