### ISSUE TITLE
Go directly to starting page

### ISSUE THREAD

**Issue by Barugon** [tchx84/Portfolio#147]
The starting page/screen with places and devices is a nice addition but there needs to be a menu item or button that takes me directly there instead of having to hit the back button many times or close and restart the app.

**Comment by tchx84** [comment]
You can, but there is a catch!

You are *supposed* to be able to just swipe-back to the home page, but there is a "bug" preventing it now.  So, try swiping back over the bottom action bar.

I will get this fixed when I am done with another project.

**Comment by Barugon** [comment]
Thanks, I'll try this out.

**Comment by tchx84** [comment]
UPDATE; The issue here is that Gtk.ListView "eats" those swipe-back gestures, and it seems there's no way to prevent that... so the only workaround here is to 1) use two-fingers swipe-back on any part of the screen, or 2) one-finger swipe-back over the bottom bar.
