### ISSUE TITLE
Allow access to the rest of the file system

### ISSUE THREAD

**Issue by arteeh** [tchx84/Portfolio#149]
I really like the way the new starting point looks, but I noticed that it's now impossible to go to places other than the user's home folder. For most cases this works fine and is safer for non-techical users, but sometimes I do want to work with the rest of the filesystem, like changing my apt sources in Debian (/etc/apt/sources.list).

I know that this might mean the app will need permissions to the whole file system, but I think it's in the spirit of the Linux smartphone that users have access to root, unlike in Android and iOS.

I would like to see a checkmark in the popover menu that, when enabled, adds "System" to the Places list, which will point to root ( / ).

**Comment by tchx84** [comment]
> I really like the way the new starting point looks, but I noticed that it's now impossible to go to places other than the user's home folder. For most cases this works fine and is safer for non-techical users, but sometimes I do want to work with the rest of the filesystem, like changing my apt sources in Debian (/etc/apt/sources.list).
> 

I am not sure if you have tried this already, but here it goes:

```
$ flatpak --user override --filesystem=host dev.tchx84.Portfolio # or use Flatseal for GUI
```

And the "System" option will show up.

If you already knew this, and you're suggesting to make it the default, as the Flatseal creator, I try to set the right example (by sticking to the minimum permissions required) to let the user decide.

> I know that this might mean the app will need permissions to the whole file system, but I think it's in the spirit of the Linux smartphone that users have access to root, unlike in Android and iOS.
> 

See instructions above.

> I would like to see a checkmark in the popover menu that, when enabled, adds "System" to the Places list, which will point to root ( / ).

That could work, I will think about it, thanks.

**Comment by arteeh** [comment]
I tried the Flatseal option, and I'm happy with it. I wasn't aware that Portfolio adds the System button when filesystem=host is enabled. You can close this if you want.

**Comment by arteeh** [comment]
I enabled filesystem=host in Flatseal and it does show root, but I suspect it's not doing it right, as if the button still points to the root inside the Flatpak sandbox. Screenshot from my laptop running Arch:

![portfoliobug](https://user-images.githubusercontent.com/35239587/112461087-e21ea200-8d5f-11eb-8353-5c2f0bd64e75.png)

To the left is nautilus in /etc. Middle is Portfolio in /etc. Right is Flatseal. I'm seeing the same issue on Mobian on my Pinephone. Having host-os and/or host-etc enabled or disabled doesn't do anything.

**Comment by tchx84** [comment]
@arteeh check /run/host/ (Flatpak thing, outside Portfolio control).
