### ISSUE TITLE
When going up a directory, please scroll the view to the just-left directory

### ISSUE THREAD

**Issue by patrakov** [tchx84/Portfolio#153]
E.g., if there are many subfolders in `/home/alarm/Documents`, when viewing files in `/home/alarm/Documents/Lab`, and then going up to `/home/alarm/Documents`, please scroll the view so that `Lab` is visible. Rationale:

1. So that unintended "going up" is easy to undo.
2. So that it is easy to visit the next one. Maybe I meant `Lab Presentations` instead.
3. Nautilus does it.

**Comment by tchx84** [comment]
@patrakov want to give this PR a try?
