### ISSUE TITLE
0.9.11 pre-release testing

### ISSUE THREAD

**Issue by tchx84** [tchx84/Portfolio#195]
@henry-nicolas @craftyguy If is not much asking, do you mind running the latest Portfolio master on your systems? I have been testing only the Flatpak version on Fedora and Arch, but I am out of bandwidth for more than that.

You can see what's new [here]( https://github.com/tchx84/Portfolio/blob/master/CHANGELOG.md) which you can use to guide your tests a bit (so is not totally random).

Thanks!

**Comment by craftyguy** [comment]
sure I'll give it a try!

**Comment by craftyguy** [comment]
Seems to work well for me, tested on postmarketOS edge (Alpine Linux edge), running phosh on the Librem 5.

It seems to be a LOT faster now with the caching stuff, and I haven't noticed any regressions over 0.9.10 with my musl compatibility patches applied (which is the current version of portfolio in pmOS).

**Comment by henry-nicolas** [comment]
I will give it a try this evening and let you know, thanks for asking.

**Comment by henry-nicolas** [comment]
Just tested it on bullseye with mobian on my pinephone and it works like a charm

**Comment by tchx84** [comment]
Thanks a lot ! @henry-nicolas @craftyguy  :mechanical_arm: 

Maybe @martinezjavier can help us too :)
