### ISSUE TITLE
copy to nextcloud

### ISSUE THREAD

**Issue by henrythemouse** [tchx84/Portfolio#196]
Nextcloud webdav mounts show up under devices. I can view them, but I can't copy to them using a PinePhone running Mobian. I verified this using mc  on the command line.  mc errors with:

`Can't chmod the target file ...`

mc offers to skip the chmod, which I do, and then the copy succeeds. The files on the PinePhone webdav all have 700 permissions whereas the local files are all 644. Using mc, if I de-select  'Preserve Attributes' the copy doesn't complain. 

Do you know if there is something that can be done with Portfolio to work around this issue? If not, perhaps there is something that can be done with nextcloud?  Anyone have any ideas?

**Comment by tchx84** [comment]
hey @henrythemouse ,

If mc can workaround it that way, I suspect there should be something that Portfolio can do as well...

I will take a look at this after this next release.

**Comment by henrythemouse** [comment]
On 2021-07-29 14:40, Martin Abente Lahaye wrote:
> hey @henrythemouse [1] ,
> 
> If mc can workaround it that way, I suspect there should be something
> that Portfolio can do as well...
> 
> I will take a look at this after this next release.
> 
> --

Thanks, sounds good.
