### ISSUE TITLE
Package for Debian

### ISSUE THREAD

**Issue by joshbowyer** [tchx84/Portfolio#20]
Putting this issue here as this is a very good candidate for a Mobian file manager, and would be good as a .deb. I will try to figure out how to do packaging however I am very new to it, otherwise I'm sure others will see this issue and want to hop in

**Comment by allnamesaretakeningithub** [comment]
This is a very good candidate for a file manager for any GNU/Linux mobile distro like PureOS or Mobian. I also have only basic skills in packaging but I can try to help

**Comment by allnamesaretakeningithub** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=977855

Seems there are more people interested in packaging this as debian, so that it can trickle down to Mobian and PureOS and others

**Comment by allnamesaretakeningithub** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=977855

Seems there are more people interested in packaging this as debian, so that it can trickle down to Mobian and PureOS and others

**Comment by tchx84** [comment]
> https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=977855
> 
> Seems there are more people interested in packaging this as debian, so that it can trickle down to Mobian and PureOS and others

Yes, @henry-nicolas is on it :)

**Comment by tchx84** [comment]
Hey @henry-nicolas , any updates on this?:)

**Comment by henry-nicolas** [comment]
Packaging work is done, it is currently pending review of my sponsor.
Once completed, it will be uploaded in Debian where it will first need to go through a review process by the ftp-master team (ensuring copyright is correctly stated and compliant with Debian policies, among other things).

Eventually we also need to figure out if we are confortable enought to make this software part of the next stable release (which freeze will start mid-Feb), related to the very new/young nature of this software.

**Comment by tchx84** [comment]
> Packaging work is done, it is currently pending review of my sponsor.
> Once completed, it will be uploaded in Debian where it will first need to go through a review process by the ftp-master team (ensuring copyright is correctly stated and compliant with Debian policies, among other things).
> 
> Eventually we also need to figure out if we are confortable enought to make this software part of the next stable release (which freeze will start mid-Feb), related to the very new/young nature of this software.

Awesome, I fixed and improved things over the last couple releases, hopefully you can still update it ;)

**Comment by henry-nicolas** [comment]
It just got accepted into Debian, see here: https://tracker.debian.org/pkg/portfolio-filemanager

Although the upload is done to experimental, which means that as-is, this will not be part of the next stable release.
That was mostly related on the very young age of the software and little user's feedback, so feel free to comment on thaat @tchx84  to share any recent developments.

**Comment by tchx84** [comment]
> It just got accepted into Debian, see here: https://tracker.debian.org/pkg/portfolio-filemanager
> 

Awesome :) I guess we can close this issue then.

> Although the upload is done to experimental, which means that as-is, this will not be part of the next stable release.
> That was mostly related on the very young age of the software and little user's feedback, so feel free to comment on that @tchx84 to share any recent developments.

That's _very_ reasonable, I am expecting to get more feedback once those Pinephones with mobian are delivered, as mobian now defaults with Portfolio.

Considering it's still in experimental, would it be possible to update the package version to the latest release?

**Comment by henry-nicolas** [comment]
> Considering it's still in experimental, would it be possible to update the package version to the latest release?

Sure, I will do that, no problem.

**Comment by tchx84** [comment]
> > Considering it's still in experimental, would it be possible to update the package version to the latest release?
> 
> Sure, I will do that, no problem.

Thanks!!
