### ISSUE TITLE
crash on startup due to null reference

### ISSUE THREAD

**Issue by raingloom** [tchx84/Portfolio#206]
```
Traceback (most recent call last):
  File "/usr/bin/dev.tchx84.Portfolio", line 40, in <module>
    from portfolio import main
  File "/usr/lib/python3.9/site-packages/portfolio/main.py", line 28, in <module>
    from .window import PortfolioWindow
  File "/usr/lib/python3.9/site-packages/portfolio/window.py", line 29, in <module>
    from .worker import PortfolioCutWorker
  File "/usr/lib/python3.9/site-packages/portfolio/worker.py", line 30, in <module>
    from .trash import default_trash
  File "/usr/lib/python3.9/site-packages/portfolio/trash.py", line 177, in <module>
    default_trash = PortfolioTrash()
  File "/usr/lib/python3.9/site-packages/portfolio/trash.py", line 41, in __init__
    self.setup()
  File "/usr/lib/python3.9/site-packages/portfolio/trash.py", line 53, in setup
    mounts = self.get_devices_trash() + [self.get_home_trash()]
  File "/usr/lib/python3.9/site-packages/portfolio/trash.py", line 91, in get_devices_trash
    path = os.path.join(mount_point, f".Trash-{os.getuid()}")
  File "/usr/lib/python3.9/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

I humbly recommend using MyPy, because based on my experience with dynamically typed languages, there is no way that a human can remember to check for null every time. These trivial errors don't slip through into releases if you use a type checker.

**Comment by tchx84** [comment]
hey @raingloom , can you provide more information about your system? distro version, desktop environment version, flatpak version, etc...

**Comment by tchx84** [comment]
Also, can you test that PR? Is not _the_ fix, but is just me trying to understand what's going ion.

**Comment by raingloom** [comment]
On Fri, 27 Aug 2021 19:04:38 -0700
Martin Abente Lahaye ***@***.***> wrote:

> hey @raingloom , can you provide more information about your system?
> distro version, desktop environment version, flatpak version, etc...
> 

distro: postmarketOS aarch64 edge
DE: None, just plain sway. I'm pretty sure it worked under Phosh.
portfolio: 0.9.12
flatpak: nope, distro package.

**Comment by raingloom** [comment]
On Fri, 27 Aug 2021 19:13:13 -0700
Martin Abente Lahaye ***@***.***> wrote:

> Also, can you test that PR? Is not _the_ fix, but is just me trying
> to understand what's going ion.
> 

I'll look into it. Bit limited on time right now.

**Comment by tchx84** [comment]
> I'll look into it. Bit limited on time right now.

No problem, I can't reproduce this (and limited on time as well) so it's up to you.

**Comment by tchx84** [comment]
@raingloom any chance you can test that PR?

**Comment by raingloom** [comment]
On Sun, 19 Sep 2021 05:04:29 -0700
Martin Abente Lahaye ***@***.***> wrote:

> @raingloom any chance you can test that PR?
> 

Sorry, had uni stuff. I'll try to test it this week.
