### ISSUE TITLE
External devices (MicroSD and drives) not shown without mouting the device first.

### ISSUE THREAD

**Issue by ahoneybun** [tchx84/Portfolio#209]
When using the application using Arch Linux ARM (ALARM) on the PinePhone 3GB model I'm not seeing the card even if I have it formatted and it shows up in `lsblk`.

**Comment by tchx84** [comment]
Have you mounted it?

**Comment by ahoneybun** [comment]
Yes does it matter where it is mounted? I tried a folder in /mnt and ~/. If it has a FAT partition it should just show up to then click and mount.

**Comment by tchx84** [comment]
weird, is this the Flatpak version or the system packaged one?

**Comment by ahoneybun** [comment]
It is the one packaged in Arch Linux ARM and it looks like it is version 0.9.12-1.

**Comment by tchx84** [comment]
weird, Ill investigate as soon as I get some free time again.

**Comment by ahoneybun** [comment]
Thank you! I would help as much as I can!

**Comment by tchx84** [comment]
@ahoneybun I current don't have a way to test it, so ill need your help:

0. Build this branch using https://github.com/tchx84/Portfolio#build-it-yourself (double check the system one is gone for the test)
1. Make sure your external SD card is **not** mounted.
2. Launch Portfolio.

In theory, this should auto-mount any volume capable of doing so..., but since I can't test I can't be completely sure about the nuances.

**Comment by ahoneybun** [comment]
I'll try that out later today!

**Comment by ahoneybun** [comment]
Alright so it doesn't show any devices using those steps on Manjaro.

**Comment by tchx84** [comment]
> Alright so it doesn't show any devices using those steps on Manjaro.

oh well, I guess I will need to figure out a way to test this.

**Comment by ahoneybun** [comment]
If you want to setup a testing flatpak repo for me to test I'll gladly do that or keep building it from source.

**Comment by ahoneybun** [comment]
Ah I think I didn't change branches, did you want me to use the auto-mount one? Sorry about that.

**Comment by ahoneybun** [comment]
Same behavior I believe.

**Comment by julianfairfax** [comment]
This is especially an issue for encrypted devices. I had to install GNOME Files to mount my encrypted Micro SD card

**Comment by tchx84** [comment]
I will come back to this ASAP (a bit busy with Flatseal ATM), but if someone wants to give it try meanwhile... more than welcome.

**Comment by tchx84** [comment]
I finally found the time to get back to this (see #215 ), and I made _some_ progress, but I need to find a usb-c dock to actually test this :sweat: ... it should work with **external** removable drives, at least. @ahoneybun if you do have such dock, can you test it?

Another thing I am trying to figure is why GIO is not detecting the internal SD drive... but well, one problem a at time.

**Comment by ahoneybun** [comment]
@tchx84 I have the hub/dock that comes with the PinePhone will that work for testing? If so can you put together a test list for me to run though?

**Comment by tchx84** [comment]
> @tchx84 I have the hub/dock that comes with the PinePhone will that work for testing? If so can you put together a test list for me to run though?

Let's start by the most simple test:

1. pull the latest from that branch (I just pushed something extra)
2. build the app and install it.
3. connect the dock and connect a usb drive to the dock
4. run Portolio
5. the usb drive should be visible on the devices section

**Comment by tchx84** [comment]
> > @tchx84 I have the hub/dock that comes with the PinePhone will that work for testing? If so can you put together a test list for me to run though?
> 
> Let's start by the most simple test:
> 
> 1. pull the latest from that branch (I just pushed something extra)
> 2. build the app and install it.
> 3. connect the dock and connect a usb drive to the dock
> 4. run Portolio
> 5. the usb drive should be visible on the devices section

Sadly, this new approach won't work either, since Gio relies on gvfs for these drive detection and volume mounting operations... I guess I am back to square one and ill need to do something else.

**Comment by tchx84** [comment]
> Oh darn.

@ahoneybun Here we go again :sweat_smile: ,  now I am trying a completely different approach. Try it with Flatpak! :)

**Comment by tchx84** [comment]
@Danct12 if you can give #223 a try, non-flatpak, as well :) it would be very much appreciated.

I suspect that on non-flatpak, this could require extra polkit similar to https://gist.github.com/Scrumplex/8f528c1f63b5f4bfabe14b0804adaba7
