### ISSUE TITLE
Make "Open With" window adaptive (please :D)

### ISSUE THREAD

**Issue by allnamesaretakeningithub** [tchx84/Portfolio#29]
The open with dialog is not adaptive making it difficult to choose an app to open a file on a mobile device. 

![open-with](https://user-images.githubusercontent.com/15075989/103090295-f7fdb900-45f0-11eb-9924-79a4e8fbfc2a.png)

![open-with-v2](https://user-images.githubusercontent.com/15075989/103090427-4448f900-45f1-11eb-8778-6963aa38c027.png)

**Comment by tchx84** [comment]
Sadly, this is not something I can fix on my end, as it is provided by the system not the app.

This can only fixed by:

A. portals upstream https://github.com/flatpak/xdg-desktop-portal, or
B. distribution who are willing to patch portals and fix it downstream.

**Comment by allnamesaretakeningithub** [comment]
understood
