### ISSUE TITLE
"Open With" always appears despite XDG default setting  

### ISSUE THREAD

**Issue by BurnyBoi** [tchx84/Portfolio#291]
When selecting to open a file with more than one application as an option, Portfolio is always bringing up the Open With dialog:

![20230323_17h29m42s_grim](https://user-images.githubusercontent.com/41203525/227368781-9db11ef7-5ffa-49f8-98f4-7a37399457ba.png)

I have double checked that I have default applications set for the file types in question:
```
$ xdg-mime  query default audio/flac
org.gnome.Lollypop.desktop

$ xdg-mime default org.gnome.Lollypop.desktop audio/flac
$
```

This is on a Librem 5 using the Flathub package

**Comment by tchx84** [comment]
Hey @BurnyBoi , thanks for bringing this up.

Unfortunately that's not something I can just "fix" that at the application level. 

All that Portfolio is doing is accessing the OpenURI portal, therefore that dialog is not part of the application,  but it's a system dialog.

I might implement a similar dialog in the future to handle "open with" and "open many" scenarios, and then I could control whether to show the dialog or not, but can't promise anything in the short term.
