### ISSUE TITLE
Hide default folders if they don’t exist

### ISSUE THREAD

**Issue by nclm** [tchx84/Portfolio#323]
My home folder does not have download, pictures, videos, etc subfolders. Currently (1.0.0), Portfolio still act like they exist, but instead just show the home folder again and again:

![Screenshot from 2023-09-01 23-49-01](https://github.com/tchx84/Portfolio/assets/923008/a32fc2f1-e657-42fa-8670-2aaff4dfa0fb)

I think those should not be displayed if the folders don’t exist?

**Comment by tchx84** [comment]
Strange, Ill check this out.. can you share your system details? distro version, flatpak version, etc.

**Comment by nclm** [comment]
This is Ubuntu 23.04, with GNOME 44.3 and Flatpak 1.14.4.

**Comment by tchx84** [comment]
@nclm can you try building https://github.com/tchx84/Portfolio/pull/324 branch and test it ?

To build, check https://github.com/tchx84/portfolio#build-it-yourself
