### ISSUE TITLE
New icon?

### ISSUE THREAD

**Issue by bertob** [tchx84/Portfolio#47]
The current icon is pretty good, but it's a little off the grid. Here's an attempt at fitting it onto the square icon template:

![image](https://user-images.githubusercontent.com/1908896/103302257-86b07280-4a03-11eb-9007-d110b800723e.png)

**Comment by tchx84** [comment]
Let's ship it! Send  a PR ?

**Comment by ahoneybun** [comment]
I don't really think it fits with the current GNOME icon set tbh.

**Comment by julianfairfax** [comment]
> I don't really think it fits with the current GNOME icon set tbh.

For what it's worth I still don't think it does. Even compared to other mobile Linux apps, it just doesn't fit in: https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/2747

**Comment by tchx84** [comment]
I like the latest version, I think is much prettier.

**Comment by julianfairfax** [comment]
I think so as well, but I still like it looks too different compared to other icons. I'm not a designer, so I don't necessarily know what makes me think that, but it really jumps out at me.

**Comment by julianfairfax** [comment]
@ahoneybun What do you think of the new icon, since you were the one to make the comment about it fitting in with the GNOME icon set?

**Comment by ahoneybun** [comment]
I think it has too many harsh shadows which doesn't match the set well but it's tough since it's not an official GNOME app anyway.

**Comment by julianfairfax** [comment]
Yeah I can see that now that you point it out. It should be more flat. I think that's what makes it stand out even with the other icons.
