### ISSUE TITLE
Icon view

### ISSUE THREAD

**Issue by philipzae** [tchx84/Portfolio#51]
Presently files/folders only appear in list view and it would be great to also have them appear in icon view. It could be toggled in the hamburger menu, or buttons can be put in the bottom toolbar next to the paste and create folder buttons.

**Comment by tchx84** [comment]
Hey @philipzae , thanks for reaching out.

The goal for portfolio is to have a minimalist file manager. This means that, supporting _all_ features that other file managers support, is explicitly a non-goal. That is one thing.

The other thing is, I am sure many people would prefer icon view over list (I have no data to support it, so arguably the same amount of people would prefer list view) but, for now, I need to focus on making the current experience solid, given my limited spare time.

Given these reasons I would I find this unlikely to happen. I hope you understand.

**Comment by philipzae** [comment]
Thanks for the consideration. I personally only use list view, but as grid/icon view is available in file manager apps on android phones, i felt it would be good addition to this file manager for linux mobile devices.
