### ISSUE TITLE
Librem 5 Gnome version support.

### ISSUE THREAD

**Issue by GNUuser** [tchx84/Portfolio#70]
I have a Librem 5 evergreen, then i want to install Portfolio but librem 5 still has a old gnome version 3.30. I am looking how install Portfolio  on gnome 3.30

**Comment by tchx84** [comment]
Why not just installing the Flatpak version?

**Comment by GNUuser** [comment]
Soy nuevo en Flatpak y es la primera vez que trato de usar Flatpak por querer instalar Portfolio, entonces instalé el soporte Flatpak en librem 5 y traté  de instalar y bajar Portfolio de Flathub entonces da error al instalar por la tienda y consola, en consola dice que nesecito gnome.3.38 y la tienda simplemnte da error de instalación.

**Comment by tchx84** [comment]
ah, tranqui...

Probá lo siguiente:

```
$ flatpak install org.gnome.Platform//3.38
$ flatpak install flathub dev.tchx84.Portfolio
```

**Comment by tchx84** [comment]
> ah, tranqui...
> 
> Probá lo siguiente:
> 
> ```
> $ flatpak install org.gnome.Platform//3.38
> $ flatpak install flathub dev.tchx84.Portfolio
> ```

Si sale sale algun error, postealo aquí y partimos de ahí.

**Comment by GNUuser** [comment]
![20210103_131132](https://user-images.githubusercontent.com/45316884/103485760-b1654700-4dc6-11eb-9565-87779e6389a8.jpg)
![20210103132127_20210103_131132](https://user-images.githubusercontent.com/45316884/103485762-b7f3be80-4dc6-11eb-8b65-346c40a9c69f.jpg)

**Comment by tchx84** [comment]
Oh dios...

**Comment by GNUuser** [comment]
Bueno por consola no dice error me equivoque al decir eso, pero me pide que baje todo esos paquetes grandes, entonces cancele el proceso, pero ahorita lo estoy corriendo de nuevo a que termine haber que pasa, pero se me hace muchos paquetes grandes para instalar Portfolio. Todavia no e seguido los pasos que me recomendastes, quiero seguir al sistema primero haber en que termina.

**Comment by tchx84** [comment]
> Bueno por consola no dice error me equivoque al decir eso, pero me pide que baje todo esos paquetes grandes, entonces cancele el proceso, pero ahorita lo estoy corriendo de nuevo a que termine haber que pasa, pero se me hace muchos paquetes grandes para instalar Portfolio. Todavia no e seguido los pasos que me recomendastes, quiero seguir al sistema primero haber en que termina.

Es básicamente lo mismo. Si quieres informarte mas sobre Runtimes en Flatpak leete esto https://docs.flatpak.org/en/latest/dependencies.html

La otra opción es instalarlo a mano desde el source (pero no es lo que recomiendo), pero vas a necesitar algunos paquetes de `-dev` para lograrlo. e.j, libhandy1.

Fijate en https://twitter.com/linmobblog/status/1341144976550490113

**Comment by GNUuser** [comment]
A terminado todo el proceso y Portfolio ya está conmigo. :  )
La aplicaciones está muy bonita, muy interesante, muy móvil. Gracias por crearla!

**Comment by GNUuser** [comment]
![20210103_134404](https://user-images.githubusercontent.com/45316884/103486247-72d18b80-4dca-11eb-9f65-010a9433693e.jpg)

**Comment by GNUuser** [comment]
Rápidamente e probado Portfolio y funciona espectacular, finalmente tengo un admistrador de archivos brutalmente facil y comfortable.

**Comment by GNUuser** [comment]
Estaria mas atractivo  si tuviese icono de archivos, entiendo que esta pleno desarrolllo Portfolio.
IconMusic.mp3
IconTar.tar
IconText.txt
IconFlakpak.flatpakref
IconETC.etc

**Comment by GNUuser** [comment]
> > Bueno por consola no dice error me equivoque al decir eso, pero me pide que baje todo esos paquetes grandes, entonces cancele el proceso, pero ahorita lo estoy corriendo de nuevo a que termine haber que pasa, pero se me hace muchos paquetes grandes para instalar Portfolio. Todavia no e seguido los pasos que me recomendastes, quiero seguir al sistema primero haber en que termina.
> 
> Es básicamente lo mismo. Si quieres informarte mas sobre Runtimes en Flatpak leete esto https://docs.flatpak.org/en/latest/dependencies.html
> 
> La otra opción es instalarlo a mano desde el source (pero no es lo que recomiendo), pero vas a necesitar algunos paquetes de `-dev` para lograrlo. e.j, libhandy1.
> 
> Fijate en https://twitter.com/linmobblog/status/1341144976550490113

Voy haber si puedo instalar  Portfolio sin flatpak desde el codigo fuente para mejor integracion y optimizacion, lo hare eventualmente primero nesecito familli
